### ISSUE TITLE
Doesn't build currently

### ISSUE THREAD

**Issue by liamsi** [citp/coniks-ref-implementation#8]
The project currently doesn't compile as it is:
- syntax error in: https://github.com/citp/coniks-ref-implementation/blob/master/coniks_server/src/org/coniks/coniks_server/UserInfoChanges.java#L62 (can send you a PR for that)
- something is wrong with the mixture of proto files, generated Java code, and the provided classes, for instance the field [unknownFields](https://github.com/citp/coniks-ref-implementation/blob/master/coniks_common/src/org/coniks/coniks_common/UtilProtos.java#L99) in `Hash` isn't defined anywhere (not in the generated class nor in the underlying `com.google.protobuf` classes). Can you compile it locally?

**Comment by masomel** [comment]
I merged the key change code in, but I haven't gotten around testing it yet (hence why issues #2 and #3 haven't been closed yet). So thank you for pointing out these problems!

If you could send a PR for the syntax error, that would be great. As for the proto files, I already compiled them locally, and that is the generated Java that is in here right now. I'm not really sure what you're seeing. I'll have to investigate this as part of my testing.

**Comment by masomel** [comment]
Closing this issue since there's a separate issue for the broken protos.

**Comment by liamsi** [comment]
Thanks for your quick reply.
