### ISSUE TITLE
Protos broke after key change code merge-in

### ISSUE THREAD

**Issue by masomel** [citp/coniks-ref-implementation#9]
From #8: something is wrong with the mixture of proto files, generated Java code, and the provided classes, for instance the field unknownFields in Hash isn't defined anywhere (not in the generated class nor in the underlying com.google.protobuf classes).

**Comment by liamsi** [comment]
From #8:

> I'm not really sure what you're seeing.

Just try building the project (either using make or whatever IDE you use). I basically see the same errors as here in travis: https://travis-ci.org/citp/coniks-ref-implementation/builds/119906980

**Comment by masomel** [comment]
Yeah, I saw it when I started using Travis. Looking into it now. Thanks again for pointing this out.

**Comment by liamsi** [comment]
No problem. Thanks again for the quick reaction :+1:

**Comment by masomel** [comment]
Fixed with commit 3f53fd8.
